//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUGPublica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUGPublica.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a park.
        /// </summary>
        internal static string AskPark {
            get {
                return ResourceManager.GetString("AskPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM ASSISTANCE.
        /// </summary>
        internal static string ConfirmEmergency {
            get {
                return ResourceManager.GetString("ConfirmEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE ABOUT TO ASK FOR ASSISTANCE.
        /// </summary>
        internal static string ConfirmEmergency2 {
            get {
                return ResourceManager.GetString("ConfirmEmergency2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO YOU WANT TO CONTINUE?.
        /// </summary>
        internal static string ConfirmEmergency3 {
            get {
                return ResourceManager.GetString("ConfirmEmergency3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON&apos;T SHOW AGAIN.
        /// </summary>
        internal static string DontShow {
            get {
                return ResourceManager.GetString("DontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events at the moment.
        /// </summary>
        internal static string EmptyEvents {
            get {
                return ResourceManager.GetString("EmptyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news at the moment.
        /// </summary>
        internal static string EmptyNews {
            get {
                return ResourceManager.GetString("EmptyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no routes at the moment.
        /// </summary>
        internal static string EmptyRoutes {
            get {
                return ResourceManager.GetString("EmptyRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the connection.
        /// </summary>
        internal static string ErrorConnection {
            get {
                return ResourceManager.GetString("ErrorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data error.
        /// </summary>
        internal static string ErrorData {
            get {
                return ResourceManager.GetString("ErrorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITIES.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTERS.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its location could not be obtained. Try again.
        /// </summary>
        internal static string GetLocationError {
            get {
                return ResourceManager.GetString("GetLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device location must be enabled.
        /// </summary>
        internal static string GPSMessageDisable {
            get {
                return ResourceManager.GetString("GPSMessageDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when performing the request for assistance.
        /// </summary>
        internal static string HelpError {
            get {
                return ResourceManager.GetString("HelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance is on the way to your location..
        /// </summary>
        internal static string HelpSuccess {
            get {
                return ResourceManager.GetString("HelpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message.
        /// </summary>
        internal static string InvalidMessage {
            get {
                return ResourceManager.GetString("InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        internal static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAKE A LOOK TO A PARK.
        /// </summary>
        internal static string LookBug {
            get {
                return ResourceManager.GetString("LookBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent successfully.
        /// </summary>
        internal static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be registered to continue.
        /// </summary>
        internal static string MustRegister {
            get {
                return ResourceManager.GetString("MustRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the network.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in the park.
        /// </summary>
        internal static string NotInsideBug {
            get {
                return ResourceManager.GetString("NotInsideBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parks.
        /// </summary>
        internal static string Parks {
            get {
                return ResourceManager.GetString("Parks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WILL FIND THESE QR CODES DISTRIBUTED ON THE PARK OR FOREST..
        /// </summary>
        internal static string QRTutorial1 {
            get {
                return ResourceManager.GetString("QRTutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACE THE QR CODE BETWEEN THE BARS AND DISCOVER INFORMATION AND SURPRISES..
        /// </summary>
        internal static string QRTutorial2 {
            get {
                return ResourceManager.GetString("QRTutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number has been successfully registered.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGULATION.
        /// </summary>
        internal static string Regulation {
            get {
                return ResourceManager.GetString("Regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the route.
        /// </summary>
        internal static string RouteDialogEndRoute {
            get {
                return ResourceManager.GetString("RouteDialogEndRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have arrived at .
        /// </summary>
        internal static string RouteDialogMessage {
            get {
                return ResourceManager.GetString("RouteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done!.
        /// </summary>
        internal static string RouteDialogTitle {
            get {
                return ResourceManager.GetString("RouteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUTES.
        /// </summary>
        internal static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR.
        /// </summary>
        internal static string ScannerQR {
            get {
                return ResourceManager.GetString("ScannerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem. Try again later..
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet the
        ///Forests of
        ///Guadalajara.
        /// </summary>
        internal static string SplashLabel {
            get {
                return ResourceManager.GetString("SplashLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any suggestions, questions or comments about Bosques Urbanos de Guadalajara?.
        /// </summary>
        internal static string SubtittleSuggestion {
            get {
                return ResourceManager.GetString("SubtittleSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        internal static string SuggestionMail {
            get {
                return ResourceManager.GetString("SuggestionMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS &amp; CONDITIONS.
        /// </summary>
        internal static string TermCondition {
            get {
                return ResourceManager.GetString("TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to hear you.
        /// </summary>
        internal static string TittleSuggestion {
            get {
                return ResourceManager.GetString("TittleSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
    }
}
