//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUGPublica.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUGPublica.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a park.
        /// </summary>
        internal static string AskPark {
            get {
                return ResourceManager.GetString("AskPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annotation.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIRM EMERGENCY.
        /// </summary>
        internal static string ConfirmEmergency {
            get {
                return ResourceManager.GetString("ConfirmEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YOU ARE ABOUT TO ASK FOR ASSISTANCE.
        /// </summary>
        internal static string ConfirmEmergency2 {
            get {
                return ResourceManager.GetString("ConfirmEmergency2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DO YOU WANT TO CONTINUE?.
        /// </summary>
        internal static string ConfirmEmergency3 {
            get {
                return ResourceManager.GetString("ConfirmEmergency3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DON&apos;T SHOW AGAIN.
        /// </summary>
        internal static string DontShow {
            get {
                return ResourceManager.GetString("DontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration:.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem with the connection.
        /// </summary>
        internal static string ErrorConnection {
            get {
                return ResourceManager.GetString("ErrorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data error.
        /// </summary>
        internal static string ErrorData {
            get {
                return ResourceManager.GetString("ErrorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTIVITIES.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILTERS.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device location must be enabled.
        /// </summary>
        internal static string GPSMessageDisable {
            get {
                return ResourceManager.GetString("GPSMessageDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem when performing the request for help.
        /// </summary>
        internal static string HelpError {
            get {
                return ResourceManager.GetString("HelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reported Emergency. Help is on the way to your location..
        /// </summary>
        internal static string HelpSuccess {
            get {
                return ResourceManager.GetString("HelpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFO.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid message.
        /// </summary>
        internal static string InvalidMessage {
            get {
                return ResourceManager.GetString("InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid name.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid phone number.
        /// </summary>
        internal static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TAKE A LOOK TO A PARK.
        /// </summary>
        internal static string LookBug {
            get {
                return ResourceManager.GetString("LookBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your message has been sent successfully.
        /// </summary>
        internal static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAP.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must be registered to continue.
        /// </summary>
        internal static string MustRegister {
            get {
                return ResourceManager.GetString("MustRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem with the network.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEWS.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are not in the park.
        /// </summary>
        internal static string NotInsideBug {
            get {
                return ResourceManager.GetString("NotInsideBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parks.
        /// </summary>
        internal static string Parks {
            get {
                return ResourceManager.GetString("Parks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROFILE.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YOU WILL FIND THESE QR CODES DISTRIBUTED ON THE PARK OR FOREST..
        /// </summary>
        internal static string QRTutorial1 {
            get {
                return ResourceManager.GetString("QRTutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLACE THE QR CODE BETWEEN THE BARS AND DISCOVER INFORMATION AND SURPRISES..
        /// </summary>
        internal static string QRTutorial2 {
            get {
                return ResourceManager.GetString("QRTutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGULATION.
        /// </summary>
        internal static string Regulation {
            get {
                return ResourceManager.GetString("Regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have completed the route.
        /// </summary>
        internal static string RouteDialogEndRoute {
            get {
                return ResourceManager.GetString("RouteDialogEndRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have arrived at .
        /// </summary>
        internal static string RouteDialogMessage {
            get {
                return ResourceManager.GetString("RouteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Well done!.
        /// </summary>
        internal static string RouteDialogTitle {
            get {
                return ResourceManager.GetString("RouteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ROUTES.
        /// </summary>
        internal static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QR.
        /// </summary>
        internal static string ScannerQR {
            get {
                return ResourceManager.GetString("ScannerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schedule.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEND.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem. Try again later..
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meet the
        ///Forests of
        ///Guadalajara.
        /// </summary>
        internal static string SplashLabel {
            get {
                return ResourceManager.GetString("SplashLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you have any suggestions, questions or comments about Bosques Urbanos de Guadalajara?.
        /// </summary>
        internal static string SubtittleSuggestion {
            get {
                return ResourceManager.GetString("SubtittleSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTACT US.
        /// </summary>
        internal static string SuggestionMail {
            get {
                return ResourceManager.GetString("SuggestionMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERMS &amp; CONDITIONS.
        /// </summary>
        internal static string TermCondition {
            get {
                return ResourceManager.GetString("TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We want to hear you.
        /// </summary>
        internal static string TittleSuggestion {
            get {
                return ResourceManager.GetString("TittleSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
